MvcCoreUtilidades/Controllers/CifradosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;

namespace MvcCoreUtilidades.Controllers
{
    public class CifradosController : Controller
    {
        public IActionResult CifradoEficiente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoEficiente
            (string contenido, string resultado, string accion)
        {
            if(accion.ToLower() == "cifrar")
            {
                //LO QUE HARMEOS SERA GUARDAR EL SALT GENERADO
                string response =
                    HelperCryptography.EncriptarContenido(contenido, false);
                ViewData["TEXTOCIFRADO"] = response;
            }else if(accion.ToLower() == "comparar")
            {
                string response =
                    HelperCryptography.EncriptarContenido(contenido, true);
                if(response != resultado)
                {
                    ViewData["MENSAJE"] = "<h1 style='color: red'>No son iguales</h1>";
                }
                else
                {
                    ViewData["MENSAJE"] = "<h1 style='color: blue'>Son iguales!!!</h1>";
                }
            }
            return View();
        }

        public IActionResult CifradoBasico()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoBasico
            (string contenido, string resultado, string accion)
        {
            //CIFRAMOS EL CONTENIDO CON EL HELPER
            string response =
                HelperCryptography.EncriptarTextoBasico(contenido);
            if(accion.ToLower() == "cifrar")
            {
                ViewData["TEXTOCIFRADO"] = response;
            }else if(accion.ToLower() == "comparar")
            {
                //COMPARAMOS EL CONTENIDO CIFRADO CON EL RESULTADO
                //DE LA CAJA
                if(response != resultado)
                {
                    ViewData["MENSAJE"] = "Los valores no coinciden";
                }
                else
                {
                    ViewData["MENSAJE"] = "Contenidos iguales!!!";
                }
            }
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Models;

namespace MvcCoreUtilidades.Controllers
{
    public class CochesController : Controller
    {
        private List<Coche> Cars;
        
        public CochesController()
        {
            this.Cars = new List<Coche>
            {
                new Coche { IdCoche = 1, Marca = "Pontiac"
                , Modelo = "Firebird", Imagen = "https://mudfeed.com/wp-content/uploads/2021/08/KITT-1200x640.jpg"},
                new Coche { IdCoche = 2, Marca = "Volkswagen"
                , Modelo = "Escarabajo", Imagen = "https://www.quadis.es/documents/80345/95274/herbie-el-volkswagen-beetle-mas.jpg"},
                new Coche { IdCoche = 3, Marca = "Ferrari"
                , Modelo = "Testarrosa", Imagen = "https://www.lavanguardia.com/files/article_main_microformat/uploads/2017/01/03/5f15f8b7c1229.png"},
                new Coche { IdCoche = 4, Marca = "Ford"
                , Modelo = "Mustang GT", Imagen = "https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/1200/public/media/image/2018/03/prueba-wolf-racing-mustang-gt.jpg"}
            };
        }

        public IActionResult Details(int idcoche)
        {
            Coche car = this.Cars.FirstOrDefault(x => x.IdCoche == idcoche);
            return View(car);
        }

        //EN LA VISTA PRINCIPAL SERA DONDE INTEGREMOS
        //LAS PETICIONES ASINCRONAS
        public IActionResult Index()
        {
            return View();
        }

        //NECESITAMOS UNA PETICION PARA CADA VISTA ASINCRONA
        //QUE VAYAMOS A UTILIZAR
        //LOS METODOS PUEDEN LLAMARSE COMO QUERAMOS, ES DECIR, 
        //DIFERENTES A LOS NOMBRES DE LAS VISTAS QUE UTILIZAN

        public IActionResult _CochePartial()
        {
            //SI VAMOS A UTILIZAR UNA VISTA PARCIAL CON AJAX
            //DEBEMOS DEVOLVER PartialView
            //PartialView DEBE TENER EL NOMBRE DE LA VISTA PARCIAL
            //Y EL MODELO SI LO NECESITAMOS
            return PartialView("_CochePartial", this.Cars);
        }

        //SI ESTAMOS UTILIZANDO PartialView, SOLAMENTE
        //PODEMOS RECIBIR PRIMITIVOS

        public IActionResult _DetailsCoche(int idcoche)
        {
            Coche car = this.Cars.FirstOrDefault(x => x.IdCoche == idcoche);
            return PartialView("_DetailsCoche", car);
        }
    }
}

MvcCoreUtilidades/Controllers/MailsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;
using System.Net;
using System.Net.Mail;

namespace MvcCoreUtilidades.Controllers
{
    public class MailsController : Controller
    {
        private HelperUploadFiles helperUploadFiles;
        private HelperMail helperMail;

        public MailsController(HelperUploadFiles helperUploadFiles
            , HelperMail helperMail)
        {
            this.helperUploadFiles = helperUploadFiles;
            this.helperMail = helperMail;
        }

        public IActionResult SendMail()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SendMail
            (string para, string asunto, string mensaje
            , List<IFormFile> files)
        {
            if (files.Count != 0)
            {
                if (files.Count > 1)
                {
                    List<string> paths =
                        await this.helperUploadFiles.UploadFileAsync
                        (files, Folders.Temporal);
                    await this.helperMail.SendMailAsync(para, asunto, mensaje, paths);
                }
                else
                {
                    string path =
                        await this.helperUploadFiles.UploadFileAsync
                        (files[0], Folders.Temporal);
                    await this.helperMail.SendMailAsync(para, asunto, mensaje, path);
                }
            }
            else
            {
                await this.helperMail.SendMailAsync(para, asunto, mensaje);
            }
            ViewData["MENSAJE"] = "Email enviado correctamente";
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/UploadFilesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;

namespace MvcCoreUtilidades.Controllers
{
    public class UploadFilesController : Controller
    {
        private HelperPathProvider helperPath;

        public UploadFilesController(HelperPathProvider helperPath)
        {
            this.helperPath = helperPath;
        }

        public IActionResult SubirFichero()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubirFichero
            (IFormFile fichero)
        {
            string fileName = fichero.FileName;
            string path = this.helperPath.MapPath(fileName, Folders.Uploads);
            using (Stream stream = new FileStream(path, FileMode.Create))
            {
                await fichero.CopyToAsync(stream);
            }
            ViewData["MENSAJE"] = "Fichero subido a " + path;
            return View();
        }
    }
}

MvcCoreUtilidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreUtilidades</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Cifrados" 
                            asp-action="CifradoEficiente">
                                Cifrado Eficiente
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Cifrados" 
                            asp-action="CifradoBasico">
                                Cifrado básico
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Mails" 
                            asp-action="SendMail">
                                Send Mails
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="UploadFiles" 
                            asp-action="SubirFichero">
                                Upload Files
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Coches" 
                            asp-action="Index">
                                Partial Views Ajax
                            </a>
                        </li>
                        @await Component.InvokeAsync("MenuCoches")
                        <partial name="_MenuUsuario" />
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCoreUtilidades/Views/Shared/_MenuUsuario.cshtml
@{
    string usuario = Context.Session.GetString("USUARIO");
}

@if(usuario == null)
{
    <li class="nav-items">
        <a asp-controller="Home"
            asp-action="Login" class="nav-link">
            Log In
        </a>
    </li>
}else {
    <li class="nav-item">
        <a asp-controller="Home" asp-action="CerrarSesion"
        class="nav-link">
            Cerrar Sesion
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Perfil</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Mis Pedidos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Comentarios</a>
    </li>
}